// <auto-generated />
using System;
using LAMAMedellin.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAMAMedellin.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LAMADbContext))]
    [Migration("20251105120846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LAMAMedellin.Domain.Entities.Comite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Comites", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            Descripcion = "Organización de eventos del capítulo",
                            FechaCreacion = new DateTime(2025, 11, 5, 12, 8, 45, 979, DateTimeKind.Utc).AddTicks(8277),
                            Nombre = "Comité de Eventos"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            Descripcion = "Gestión de comunicación interna y externa",
                            FechaCreacion = new DateTime(2025, 11, 5, 12, 8, 45, 979, DateTimeKind.Utc).AddTicks(8282),
                            Nombre = "Comité de Comunicaciones"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            Descripcion = "Desarrollo de proyectos de impacto social",
                            FechaCreacion = new DateTime(2025, 11, 5, 12, 8, 45, 979, DateTimeKind.Utc).AddTicks(8290),
                            Nombre = "Comité de Proyectos Sociales"
                        });
                });

            modelBuilder.Entity("LAMAMedellin.Domain.Entities.Miembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Profesion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoMembresia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.HasIndex("TipoMembresia");

                    b.ToTable("Miembros", (string)null);
                });

            modelBuilder.Entity("LAMAMedellin.Domain.Entities.MiembroComite", b =>
                {
                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsCoordinador")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MiembroId", "ComiteId");

                    b.HasIndex("ComiteId");

                    b.ToTable("MiembroComites", (string)null);
                });

            modelBuilder.Entity("LAMAMedellin.Domain.Entities.MiembroComite", b =>
                {
                    b.HasOne("LAMAMedellin.Domain.Entities.Comite", "Comite")
                        .WithMany("Miembros")
                        .HasForeignKey("ComiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAMAMedellin.Domain.Entities.Miembro", "Miembro")
                        .WithMany("Comites")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comite");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("LAMAMedellin.Domain.Entities.Comite", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("LAMAMedellin.Domain.Entities.Miembro", b =>
                {
                    b.Navigation("Comites");
                });
#pragma warning restore 612, 618
        }
    }
}
